import { defineConfig, devices } from "@playwright/test";

/**
 * Local-stack Supabase demo values (same as lib/supabase/env.ts fallbacks).
 * These are well-known, non-secret JWT tokens generated by `supabase start` on
 * every local Supabase CLI project — safe to commit. Production values come
 * from the deployment environment (never committed).
 */
const LOCAL_SUPABASE_URL = "http://127.0.0.1:64321";
const LOCAL_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";
const LOCAL_SERVICE_ROLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";
const LOCAL_DB_URL =
  "postgresql://postgres:postgres@127.0.0.1:64322/postgres";

export default defineConfig({
  testDir: "e2e",
  // The single `next start` server wedges under parallel load (false failures
  // observed in review), so run serially with one worker.
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: "list",
  use: {
    baseURL: "http://localhost:3000",
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  // Phase 5 (I-005): e2e runs against `next start` with the Supabase local
  // stack. The webServer env explicitly sets the Supabase URL/keys and
  // DATABASE_URL so the production build connects to the local stack — the
  // lib/supabase/env.ts defaults (same values) are the fallback for cases
  // where these are not set. reuseExistingServer: true locally so an
  // already-running server is reused.
  webServer: {
    command: "pnpm start",
    url: "http://localhost:3000",
    reuseExistingServer: !process.env.CI,
    timeout: 60_000,
    env: {
      // Supabase local stack (Phase 5 — re-prove e2e on Supabase Auth)
      NEXT_PUBLIC_SUPABASE_URL:
        process.env.NEXT_PUBLIC_SUPABASE_URL ?? LOCAL_SUPABASE_URL,
      NEXT_PUBLIC_SUPABASE_ANON_KEY:
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? LOCAL_ANON_KEY,
      SUPABASE_SERVICE_ROLE_KEY:
        process.env.SUPABASE_SERVICE_ROLE_KEY ?? LOCAL_SERVICE_ROLE_KEY,
      DATABASE_URL:
        process.env.DATABASE_URL ?? LOCAL_DB_URL,
      // Keycard HMAC secret — `pnpm start` is a production build, where token.ts
      // fails closed if this is unset. CI/e2e provide a test value like any deploy.
      KEYCARD_TOKEN_SECRET:
        process.env.KEYCARD_TOKEN_SECRET ?? "flowspace-keycard-e2e-secret",
      // Supabase local stack (and `next start`) needs this on localhost (non-HTTPS).
      AUTH_TRUST_HOST: "true",
    },
  },
});
