/**
 * Shared application-level types.
 *
 * Domain entity types are generated by Prisma (`@prisma/client`); keep this for
 * cross-cutting types (API envelopes, tenancy context, etc.).
 */

/** Resolved tenant context passed through server requests. */
export interface TenantContext {
  orgId: string;
}
